#!/usr/bin/env node

/**
 * Notes Agent - Project Documentation Generator
 * 
 * Usage:
 *   node notes-agent.js init          # Initialize documentation files
 *   node notes-agent.js update         # Update existing files
 *   node notes-agent.js session        # Add session summary
 *   node notes-agent.js note           # Add important note/decision
 *   node notes-agent.js summary        # Generate project summary
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const CONFIG_FILE = 'notes-agent/config.json';
const PROJECT_NOTES = 'PROJECT_NOTES.md';
const DEPLOYMENT_LOG = 'DEPLOYMENT_LOG.md';
const SESSION_LOG = 'SESSION_LOG.md';

// Load or create config
function loadConfig() {
  const configPath = path.join(process.cwd(), CONFIG_FILE);
  if (fs.existsSync(configPath)) {
    return JSON.parse(fs.readFileSync(configPath, 'utf8'));
  }
  return {
    projectName: path.basename(process.cwd()),
    projectType: 'unknown',
    urls: {},
    credentials: {},
    notes: [],
    sessions: [],
    deployments: [],
    troubleshooting: []
  };
}

function saveConfig(config) {
  const configPath = path.join(process.cwd(), CONFIG_FILE);
  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
}

function generateProjectNotes(config) {
  const date = new Date().toISOString().split('T')[0];
  
  return `# Project Notes - ${config.projectName}

> Last Updated: ${date}
> Project Type: ${config.projectType}

## Critical Information

### Live URLs
${Object.entries(config.urls).map(([key, value]) => `- **${key}**: ${value}`).join('\n') || '- None configured'}

### Key Configurations
${Object.entries(config.credentials).map(([key, value]) => {
  const location = typeof value === 'string' ? value : value.location || 'Not stored here';
  const note = typeof value === 'object' && value.note ? ` (${value.note})` : '';
  return `- **${key}**: ${location}${note}`;
}).join('\n') || '- None configured'}

### Environment Variables
See \`.env.example\` for required variables. Production values stored in:
${config.deployment?.envLocation || 'AWS Amplify / Deployment platform'}

## Important Decisions & Fixes

${config.notes && config.notes.length > 0 ? config.notes.map(note => `### ${note.date} - ${note.title}
- **Issue**: ${note.issue}
- **Solution**: ${note.solution}
- **Files Changed**: ${note.files?.join(', ') || 'N/A'}
- **Related**: ${note.related || 'N/A'}
`).join('\n') : '- No notes yet'}

## Troubleshooting Log

${config.troubleshooting && config.troubleshooting.length > 0 ? config.troubleshooting.map(item => `### ${item.date} - ${item.issue}
- **Problem**: ${item.problem}
- **Solution**: ${item.solution}
- **Prevention**: ${item.prevention || 'N/A'}
`).join('\n') : '- No troubleshooting entries yet'}

## Deployment Information

### Current Deployment
- **Platform**: ${config.deployment?.platform || 'Not configured'}
- **Status**: ${config.deployment?.status || 'Unknown'}
- **Last Deployed**: ${config.deployment?.lastDeployed || 'Never'}
${config.deployment?.appId ? `- **App ID**: ${config.deployment.appId}` : ''}
${config.deployment?.region ? `- **Region**: ${config.deployment.region}` : ''}

### Deployment Checklist
- [ ] Environment variables configured
- [ ] Database migrations run
- [ ] Tests passing
- [ ] Documentation updated
- [ ] Secrets stored securely

## Quick Reference

### Common Commands
\`\`\`bash
${config.commands && config.commands.length > 0 ? config.commands.join('\n') : '# Add common commands here'}
\`\`\`

### Related Documentation
${config.documentation && config.documentation.length > 0 ? config.documentation.map(doc => `- [${doc.title}](${doc.path})`).join('\n') : '- None'}

---
*Generated by Notes Agent - Run \`node notes-agent/notes-agent.js update\` to refresh*
`;
}

function generateDeploymentLog(config) {
  return `# Deployment Log - ${config.projectName}

> Track all deployments and changes

${config.deployments && config.deployments.length > 0 ? config.deployments.map(deploy => `## ${deploy.date} - ${deploy.version || 'Deployment'}
- **Status**: ${deploy.status}
- **Changes**: ${deploy.changes}
- **Commit**: ${deploy.commit || 'N/A'}
- **Notes**: ${deploy.notes || 'None'}
`).join('\n') : '- No deployments logged yet'}

---
*Add entries manually or update config.json*
`;
}

function generateSessionLog(config) {
  return `# Session Log - ${config.projectName}

> Summary of work sessions and important discoveries

${config.sessions && config.sessions.length > 0 ? config.sessions.map(session => `## ${session.date} - ${session.title}
- **Duration**: ${session.duration || 'Unknown'}
- **What Was Done**: ${session.summary}
- **Key Decisions**: ${session.decisions?.join('; ') || 'None'}
- **Files Changed**: ${session.files?.join(', ') || 'None'}
- **Blockers**: ${session.blockers?.join('; ') || 'None'}
- **Next Steps**: ${session.nextSteps?.join('; ') || 'None'}
`).join('\n') : '- No sessions logged yet'}

---
*Add sessions with: \`node notes-agent/notes-agent.js session\`*
`;
}

function init() {
  const config = loadConfig();
  
  console.log('📝 Notes Agent - Initializing...');
  console.log('');
  
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  
  rl.question('Project Type (Next.js, React, Node.js, etc.): ', (type) => {
    config.projectType = type || 'unknown';
    
    rl.question('Production URL (optional, press Enter to skip): ', (url) => {
      if (url) {
        config.urls.production = url;
      }
      
      rl.question('Staging URL (optional, press Enter to skip): ', (stagingUrl) => {
        if (stagingUrl) {
          config.urls.staging = stagingUrl;
        }
        
        saveConfig(config);
        updateFiles(config);
        
        console.log('');
        console.log('✅ Documentation files initialized!');
        console.log(`📄 Created: ${PROJECT_NOTES}`);
        console.log(`📄 Created: ${DEPLOYMENT_LOG}`);
        console.log(`📄 Created: ${SESSION_LOG}`);
        console.log(`📄 Created: ${CONFIG_FILE}`);
        console.log('');
        console.log('💡 Run "node notes-agent/notes-agent.js update" to refresh documentation');
        console.log('💡 Run "node notes-agent/notes-agent.js session" to add a session summary');
        
        rl.close();
      });
    });
  });
}

function updateFiles(config) {
  fs.writeFileSync(PROJECT_NOTES, generateProjectNotes(config));
  fs.writeFileSync(DEPLOYMENT_LOG, generateDeploymentLog(config));
  fs.writeFileSync(SESSION_LOG, generateSessionLog(config));
}

function addSession() {
  const config = loadConfig();
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  
  console.log('📝 Add Session Summary');
  console.log('---');
  console.log('');
  
  const session = {
    date: new Date().toISOString().split('T')[0],
    title: '',
    summary: '',
    decisions: [],
    files: [],
    blockers: [],
    nextSteps: []
  };
  
  rl.question('Session Title: ', (title) => {
    session.title = title;
    
    rl.question('What was done (summary): ', (summary) => {
      session.summary = summary;
      
      rl.question('Key decisions (comma-separated, or Enter to skip): ', (decisions) => {
        if (decisions) {
          session.decisions = decisions.split(',').map(d => d.trim());
        }
        
        rl.question('Files changed (comma-separated, or Enter to skip): ', (files) => {
          if (files) {
            session.files = files.split(',').map(f => f.trim());
          }
          
          rl.question('Blockers encountered (comma-separated, or Enter to skip): ', (blockers) => {
            if (blockers) {
              session.blockers = blockers.split(',').map(b => b.trim());
            }
            
            rl.question('Next steps (comma-separated, or Enter to skip): ', (nextSteps) => {
              if (nextSteps) {
                session.nextSteps = nextSteps.split(',').map(s => s.trim());
              }
              
              if (!config.sessions) config.sessions = [];
              config.sessions.unshift(session);
              saveConfig(config);
              updateFiles(config);
              
              console.log('');
              console.log('✅ Session added to documentation!');
              rl.close();
            });
          });
        });
      });
    });
  });
}

function addNote() {
  const config = loadConfig();
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  
  console.log('📝 Add Important Note/Decision');
  console.log('---');
  console.log('');
  
  const note = {
    date: new Date().toISOString().split('T')[0],
    title: '',
    issue: '',
    solution: '',
    files: [],
    related: ''
  };
  
  rl.question('Note Title: ', (title) => {
    note.title = title;
    
    rl.question('Issue/Problem: ', (issue) => {
      note.issue = issue;
      
      rl.question('Solution: ', (solution) => {
        note.solution = solution;
        
        rl.question('Files Changed (comma-separated, or Enter to skip): ', (files) => {
          if (files) {
            note.files = files.split(',').map(f => f.trim());
          }
          
          rl.question('Related Info (links, references, etc.): ', (related) => {
            note.related = related;
            
            if (!config.notes) config.notes = [];
            config.notes.unshift(note);
            saveConfig(config);
            updateFiles(config);
            
            console.log('');
            console.log('✅ Note added to documentation!');
            rl.close();
          });
        });
      });
    });
  });
}

// Main command handler
const command = process.argv[2];

switch (command) {
  case 'init':
    init();
    break;
  case 'update':
    updateFiles(loadConfig());
    console.log('✅ Documentation updated!');
    break;
  case 'session':
    addSession();
    break;
  case 'note':
    addNote();
    break;
  case 'summary': {
    const configSummary = loadConfig();
    console.log('');
    console.log('📊 Project Summary');
    console.log('==================');
    console.log(`Project: ${configSummary.projectName}`);
    console.log(`Type: ${configSummary.projectType}`);
    console.log(`Notes: ${configSummary.notes?.length || 0}`);
    console.log(`Sessions: ${configSummary.sessions?.length || 0}`);
    console.log(`Deployments: ${configSummary.deployments?.length || 0}`);
    console.log(`Troubleshooting Entries: ${configSummary.troubleshooting?.length || 0}`);
    console.log('');
    break;
  }
  default:
    console.log('\n📝 Notes Agent - Project Documentation Generator\n');
    console.log('Usage:');
    console.log('  node notes-agent/notes-agent.js init          Initialize documentation files');
    console.log('  node notes-agent/notes-agent.js update        Update existing documentation');
    console.log('  node notes-agent/notes-agent.js session       Add a session summary');
    console.log('  node notes-agent/notes-agent.js note          Add an important note/decision');
    console.log('  node notes-agent/notes-agent.js summary       Show project summary');
    console.log('\nFor more info, see notes-agent/README.md\n');
    break;
}




